# Numpy
### can only contain elements of same type compatoble with C/C++ types

In [2]:
import numpy as np

In [5]:
first_array = np.array([1, 2, 4, 5])
first_array

array([1, 2, 4, 5])

In [7]:
first_array.dtype

dtype('int32')

In [9]:
float_array = np.array([2.5, 3.2, 1.1])
float_array

array([2.5, 3.2, 1.1])

In [10]:
float_array.dtype

dtype('float64')

In [11]:
float_array[0]

2.5

In [12]:
float_array[2] = 42.0

In [13]:
float_array

array([ 2.5,  3.2, 42. ])

In [14]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
some_matrix = np.array([[1,2,3], [4,5,6]])

In [18]:
some_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
some_matrix.shape

(2, 3)

In [20]:
some_matrix[1, 1]

5